name: nonreg-demos-courses_ubuntu-latest

on:
  # Activate the workflow at each pull request on dev branch
  pull_request:
    branches: [ dev ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  call-python:
    uses: ./.github/workflows/nonreg-demos-courses_python_ubuntu-latest.yml
  call-r:
    uses: ./.github/workflows/nonreg-demos-courses_r_ubuntu-latest.yml
